### ISSUE TITLE
Error creating transaction with MetaMask: Internal JSON-RPC error

### ISSUE THREAD

**Issue by domagojlatecki** [OriginTrail/dkg.js#113]
I was trying to create an asset via DKG.js API call in the browser using MetaMask as wallet provider. The asset was successfully created when running the example via Node. The main difference in the configuration was that in Node I provided `privateKey` and `publicKey` via `blockchain` config:

```javascript
new DkgClient({
    endpoint: 'http://******',
    port: 8900,
    blockchain: {
        name: 'otp::testnet',
        publicKey: "*******",
        privateKey: "*******"
    }
});
```

When running the example in the browser, I did not provide `privateKey` and `publicKey` as I wanted to use MetaMask wallet provider. So the config was:

```javascript
new DkgClient({
    endpoint: 'http://******',
    port: 8900,
    blockchain: {
        name: 'otp::testnet'
    }
});
```

This lack of `privateKey` and `publicKey` in config was causing the following MetaMask error when trying to create an asset:

![Screenshot 2023-11-03 at 13 20 21](https://github.com/OriginTrail/dkg.js/assets/12549625/29ea3037-d03e-43a9-938b-318fcd896f4b)

After some attempts with different configurations, I noticed that the example was working in the browser with MetaMask when I provided the `publicKey` value:

```javascript
new DkgClient({
    endpoint: 'http://******',
    port: 8900,
    blockchain: {
        name: 'otp::testnet',
        publicKey: "*******"
    }
});
```

After that I started digging through the DKS.js code and I noticed the way that the `gasLimit` is calculated when using MetaMask is as follows:

```javascript
const gasLimit = await contractInstance.methods[functionName](...args).estimateGas({
    from: blockchain.publicKey,
});
```

This code is located in the `services/blockchain-service/blockchain-service-base.js` file, in the function `prepareTransaction` (lines 69-95) which is called from `services/blockchain-service/implementations/browser-blockchain-service.js` (line 56).

The thing is that `blockchain.publicKey` here will be `null` if it was not specified in the above mentioned configuration, causing the MetaMask error. Immediately before `gasLimit` calculation, there is a call to fetch `publicKey`:

```javascript
const publicKey = await this.getPublicKey(blockchain);
```

which is then **not used** for the `estimateGas` contract call, effectively ignoring the MetaMask wallet address. Instead, the empty configuration `publicKey` is used. Could it be that this was an oversight when writing the part of the code that calculates the gas limit? Should the contract call to `estimateGas` be:

```javascript
const publicKey = await this.getPublicKey(blockchain);
const gasLimit = await contractInstance.methods[functionName](...args).estimateGas({
    from: publicKey,
});
```

or even:

```javascript
const publicKey = await this.getPublicKey(blockchain);
const gasLimit = await contractInstance.methods[functionName](...args).estimateGas({
    from: blockchain.publicKey || publicKey,
});
```

since then call to `estimateGas` will not have `null` value for `from` address?

**Comment by brkagithub** [comment]
Hey @domagojlatecki, thanks a lot for reporting the issue. Definitely seems like an oversight on our side just like you explained, we will prioritize this next week and let you know when the issue is resolved.
