### ISSUE TITLE
React + MetaMask Internal JSON RPC error: { code: -32602, message: "duplicate field `data` at line 1 column 270" }

### ISSUE THREAD

**Issue by CosmiCloud** [OriginTrail/dkg.js#89]
I am attempting to initialize MetaMask in my 'Request' react component that has been passed my txn data to publish an asset. This could be entirely my issue as I am relatively new to React.

You can see the current file here: https://github.com/CosmiCloud/othub-react/blob/master/src/pages/portal/Request.js

 I would first like to call out a few things:
1. I have included window.Buffer = window.Buffer || require("buffer").Buffer; at the top of the component file before the dkg.js SDK throws 'Buffer is not defined'. I am unsure if this is a valid fix, but it resolves the error.

2. I must use window.DkgClient.asset.create even though the vue demo file shows to use DkgClient.asset.create. When I try the latter, DkgClient is not defined. I can console.log(window.DkgClient) and initializing and the object looks fine.
![Capture1](https://github.com/OriginTrail/dkg.js/assets/42195091/8bd9a25f-1fe4-43d9-9bf2-2219e1b9fb5a)

 Below you can see the asset data being used, the publish options, and the full MetaMask RPC error:
![Capture](https://github.com/OriginTrail/dkg.js/assets/42195091/84e10427-225d-4ae4-a45a-ef30e232065f)

Package.json: https://github.com/othub-io/othub-react/blob/master/package.json

**Comment by FamousAmos-ChillZone** [comment]
Hallo, hoping there is a resolution to this as a fellow react builder.

**Comment by NZT48** [comment]
Hi guys, thanks for reporting the issue, we have planned to tackle it soon, we will ping you if we need more info but I think that we have enough and now how to approach solving the issue.

**Comment by lukeskinner** [comment]
Hello! Adding a +1 to this as im using othub for publishing assets for my project im building on the dkg. My momentum on my project is slowed since i cant publish via othub (cosmi)

**Comment by brkagithub** [comment]
Hey guys,

Both the Buffer issue and the DKG operations not working from the client side should be fixed with the 6.0.9 release. Just bump the version and make sure your Metamask is connected and on the right network. We tested it with Create React App which @CosmiCloud I'm pretty sure you used too and with both local hardhat and OTP testnet networks.

Thanks a lot for reporting the issue, if you encounter more of them please feel free to write here or ping us on Discord!

**Comment by CosmiCloud** [comment]
@brkagithub This update has definitely improved the functionality. However, when I try to sign the 2nd transaction for the first time, I receive another JSON RPC error:
![Screenshot 2023-08-25 090747](https://github.com/OriginTrail/dkg.js/assets/42195091/f364fd56-6be9-4b37-a27d-527c3ad0e62a)

All other subsequent approval attempts from the wallet fail at the first transaction with the same error.

If I switch wallets, I get the same experience of 2nd txn failing and all subsequent txns failing afterwards.

**Comment by brkagithub** [comment]
Hey @CosmiCloud,

From what I understand you're trying to create an asset. I have a public repo where I tested the issue so looking at that might help you https://github.com/brkagithub/dkgjs-browser-issue/blob/master/src/App.js. The only difference from what I see is that you use SSL: true, but even when I enabled the option I'm able to publish the asset

**Comment by CosmiCloud** [comment]
Hey @brkagithub ,

I found the issue in my code. I was not specifying publicKey in my blockchain options. It was my bad for assuming it would take the currently connected wallet. Minting assets no problems now :)

**Comment by brkagithub** [comment]
amazing, good job and hope everything works from now on @CosmiCloud :D
