### ISSUE TITLE
NextJS13 App Router - (Unable To Do Any CRUT Operations)

### ISSUE THREAD

**Issue by FamousAmos-ChillZone** [OriginTrail/dkg.js#90]
A few weeks ago I created an issue about the DKG not compiling with Nextjs13. However, i'm not able to perform any CRUT operations now that the time has come for such actions. Pulling in the node version and such works just fine. Also, still encountering theses compilation errors:

Critical dependency: the request of a dependency is an expression

Module not found: Can't resolve 'encoding' in '/node_modules/cross-fetch/node_modules/node-fetch/lib'

Import trace for requested module:
./node_modules/cross-fetch/node_modules/node-fetch/lib/index.js
./node_modules/cross-fetch/dist/node-ponyfill.js
./node_modules/cross-fetch/dist/node-polyfill.js
./node_modules/web3-providers-http/lib/index.js
./node_modules/web3-core-requestmanager/lib/index.js
./node_modules/web3-core/lib/index.js
./node_modules/web3/lib/index.js
./node_modules/dkg.js/services/blockchain-service/implementations/browser-blockchain-service.js
./node_modules/dkg.js/services/blockchain-service/blockchain-interface.js
./node_modules/dkg.js/services/base-service-manager.js
./node_modules/dkg.js/index.js
./app/page.js

Import trace for requested module:
./node_modules/keyv/src/index.js
./node_modules/cacheable-request/src/index.js
./node_modules/swarm-js/node_modules/got/dist/source/core/index.js
./node_modules/swarm-js/node_modules/got/dist/source/create.js
./node_modules/swarm-js/node_modules/got/dist/source/index.js
./node_modules/swarm-js/lib/files.js
./node_modules/swarm-js/lib/api-node.js
./node_modules/web3-bzz/lib/index.js
./node_modules/web3/lib/index.js
./node_modules/dkg.js/services/blockchain-service/implementations/browser-blockchain-service.js
./node_modules/dkg.js/services/blockchain-service/blockchain-interface.js
./node_modules/dkg.js/services/base-service-manager.js
./node_modules/dkg.js/index.js
./app/page.js

**Comment by brkagithub** [comment]
hello, I did not manage to reproduce this with NextJS 13.4.4 and dkg.js 6.0.6 or 6.0.7 (tried both) on NodeJS 16.6.0 (this version is definitely stable). A good thing to try would be to downgrade the Node version, but if that fails let us know - also someone else from the team will see if they can reproduce the error since I cannot.

**Comment by FamousAmos-ChillZone** [comment]
Thank you, will give this a shot. Not sure what is going on. Will test this out

**Comment by NZT48** [comment]
@FamousAmos-ChillZone do you still experience this issue?

**Comment by FamousAmos-ChillZone** [comment]
Hello, this issue has been resolved!

**Comment by FamousAmos-ChillZone** [comment]
Hello, this issue has been resolved! Everything works fine!
